executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p PRJNA559322/logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=PRJNA559322/logs/{rule}/{rule}-{wildcards}-%j.out
    --time={resources.runtime}
    --parsable
cluster-generic-cancel-cmd: scancel
cluster-generic-cancel-nargs: 50

default-resources:
  - partition=medium
  - mem_mb=4000
  - runtime="12h"

resources:
  singleton: 1

restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 32
keep-going: True
rerun-incomplete: True
printshellcmds: False
scheduler: greedy

use-conda: True
conda-prefix: $HOME/.cache/snakemake/conda
conda-frontend: mamba

